import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  specSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'MANIFESTO',
      label: 'Manifesto',
    },
    {
      type: 'category',
      label: 'Quick Start',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: '00_shortcut'},
      ],
    },
    {
      type: 'category',
      label: '1. LLMFeed Core',
      collapsed: false,
      items: [
        {type: 'autogenerated', dirName: '01_llmfeed'},
      ],
    },
    {
      type: 'category',
      label: '2. Feed Types',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: '02_llmfeed_feedtype'},
      ],
    },
    {
      type: 'category',
      label: '3. Extensions',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: '03_llmfeed_extensions'},
      ],
    },
    {
      type: 'category',
      label: '4. Agent Behavior',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: '04_agent-behavior'},
      ],
    },
    {
      type: 'category',
      label: '5. Examples',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: '05_examples'},
      ],
    },
    {
      type: 'category',
      label: '7. Vision & Roadmap',
      collapsed: true,
      items: [
        {type: 'autogenerated', dirName: '07_vision'},
      ],
    },
    {
      type: 'doc',
      id: 'ADOPTION',
      label: 'Adoption Guide',
    },
  ],
};

export default sidebars;
